### ISSUE TITLE
does it support Windows?

### ISSUE THREAD

**Issue by 88JC** [Karmaz95/crimson#2]
does Crimson support windowsdoes Crimson support windows i hope it will rival nuclei and recconftw And I don't want to use the burp suite how do I do that?

**Comment by Karmaz95** [comment]
Hi, unfortunately not yet.

Docker will be introduced in the future, to support all platforms.

If you want to use it on Windows, you have to install Vmware / Virtual box and virtualize the Linux system (preferred Linux Mint).

If you want to use it without Burp Suite, just enter random data in the collaborator placeholder. 
Burp Suite functionalities will be omitted, but if you see any error, just comment out those functionalities.

**Comment by 88JC** [comment]
I hope you make clear and understandable documentation so that new beginners have no trouble, thank

**Comment by Karmaz95** [comment]
Yes, of course! I will upload documentation when I finish "dockerizing" the project.

**Comment by Karmaz95** [comment]
Hello, the container is ready, you can use it on WIndows OS from now!
