### ISSUE TITLE
Github-search for enumerating  urls and secret tokens

### ISSUE THREAD

**Issue by pwneddesal** [Karmaz95/crimson#3]
Please include Github-search for enumerating  URLs and secret tokens as well .thanks

**Comment by Karmaz95** [comment]
Hi!,

do you mean [TruffleHog-like tools](https://github.com/trufflesecurity/truffleHog)?

If yes, it will be added in the next patch for sure, stay tuned!

**Comment by pwneddesal** [comment]
and also https://github.com/gwen001/github-search. Github may contain URLs and secrets as well

**Comment by Karmaz95** [comment]
I've added this to my TODO list. Thanks for the suggestions!
